name: Create Reset Branch

on:
  workflow_dispatch:

jobs:
  reset-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Create orphan branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create orphan branch
          git checkout --orphan reset

          # Remove old files from index
          git rm -rf .

      - name: Copy files from master
        run: |
          # Checkout master into temp folder
          git checkout master -- .
          
          # Add and commit
          git add .
          git commit -m "Initial commit on reset branch"

      - name: Push reset branch
        run: git push origin reset --force
